# Create data and config as required by kwb.rabimo from Berlin data delivered by
# Leilah in March 2025

library(dplyr)

read_berlin_data <- function(file_roads, file_blocks) {
  read_without_geom <- function(file) {
    data <- sf::read_sf(file)
    data$Shape <- NULL
    data
  }
  as.data.frame(dplyr::bind_rows(
    block = read_without_geom(file_blocks),
    road = read_without_geom(file_roads),
    .id = "category"
  ))
}

get_district_map <- function(berlin_data) {
  district_map <- berlin_data %>%
    dplyr::group_by(bez, bezirk) %>%
    dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
    dplyr::filter(!is.na(bezirk), n > 3L) %>%
    dplyr::arrange(bez, bezirk) %>%
    dplyr::mutate(bez = as.integer(bez)) %>%
    dplyr::select(-n) %>%
    as.data.frame()
  stopifnot(all(table(district_map$bezirk) == 1L))
  stopifnot(all(sort(district_map$bezirk) == seq_along(district_map$bezirk)))
  district_map
}

get_evaporation_config <- function(berlin_data, epot_data) {
  epot_not_waterbody <- dplyr::left_join(
    x = get_district_map(berlin_data),
    y = epot_data,
    by = "bez"
  ) %>%
    dplyr::select(-bez) %>%
    dplyr::rename(district = bezirk) %>%
    dplyr::mutate(is_waterbody = FALSE) %>%
    dplyr::relocate(is_waterbody) %>%
    dplyr::arrange(district)

  # Add default evaporation (district = NA)
  epot_not_waterbody_default <- epot_not_waterbody %>%
    dplyr::summarise(
      etp = as.integer(round(mean(etp))),
      etps = as.integer(round(mean(etps)))
    ) %>% cbind(
      is_waterbody = FALSE,
      district = NA
    )

  # Use old waterbody evaporation (we do not know how to recalculate)
  epot_waterbody <- kwb.abimo::read_config() %>%
    kwb.rabimo::abimo_config_to_config() %>%
    kwb.utils::selectElements("potential_evaporation") %>%
    dplyr::filter(is_waterbody) %>%
    dplyr::arrange(district)

  rbind(
    epot_waterbody,
    epot_not_waterbody,
    epot_not_waterbody_default
  )
}

berlin_data <- read_berlin_data(
  file_roads = "C:/Users/hsonne/Downloads/A/abimo_hyras9120.gdb20250310/abimo_hyras9120.gdb/a00000009.gdbtable",
  file_blocks = "C:/Users/hsonne/Downloads/A/abimo_hyras9120.gdb20250310/abimo_hyras9120.gdb/a0000000a.gdbtable"
)

# Read evaporation table (generated by inst/scripts/epot-raster-to-district.R)
epot_data <- readRDS("~/../Downloads/A/abimo/epot_91-20.rds") %>%
  dplyr::select(bez = "ID", etp = total_mean, etps = summer_mean)

# Read existing config
config <- kwb.rabimo::rabimo_inputs_2020$config

# Remove entries
config$swale <- NULL
config$result_digits <- NULL

# Add precipitation correction factor and potential evaporation
config$precipitation_correction_factor <- 1.09
config$potential_evaporation <- get_evaporation_config(berlin_data, epot_data)

berlin_data_new <- kwb.rabimo:::prepare_input_data(berlin_data, config = config)

kwb.rabimo::run_rabimo(berlin_data_new, config = config)

